version: '3'

services:
  mongodb:
    image: 'mongo'
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  api:
    build: './perf-analytics-api'
    ports:
    - "3002:3002"
  js:
    build: './perf-analytics-js'
    ports:
    - "3001:3001"
  dashboard:
    build: './perf-analytics-dashboard'
    ports:
    - "3000:3000"
