version: '3'

services:
  mongo:
    image: 'mongo'
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    networks:
      - app-network
  api:
    build: './perf-analytics-api'
    ports:
    - "3002:3002"
    depends_on:
      - mongo
    networks:
      - app-network
  js:
    build: './perf-analytics-js'
    ports:
    - "3001:3001"
    networks:
      - app-network
  dashboard:
    build: './perf-analytics-dashboard'
    ports:
    - "3000:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
